services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1.5.0
    container_name: pocket-id
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - 1411:1411
    labels:
      komodo.skip:
      tsdproxy.enable: "true"
      tsdproxy.name: "id"
      tsdproxy.autodetect: "false"
      tsdproxy.port.1: "443/https:1411/http"
      tsdproxy.port.2: "80/http->${APP_URL}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/${SERVICE}/data:/app/data
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  proxy:
    external: true
