services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    networks:
      - management
    ports:
      - 3030:3030
    environment:
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_PORT: 3030
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/services/semaphore/config:/etc/semaphore
      - /opt/services/semaphore/data:/var/lib/semaphore

networks:
  management:
    external: true
