services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    command: --quiet --wiredTigerCacheSizeGB 0.25
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    labels:
      komodo.skip: 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/mongo/data:/data/db
      - ${SERVICE_PATH}/mongo/config:/data/configdb

networks:
  db:
    external: true
