services:
  komodo-agent:
    image: ghcr.io/moghtech/komodo-periphery:1.18.4
    container_name: komodo-agent
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - management
    ports:
      - 8120:8120
    labels:
      komodo.skip:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${SERVICE_PATH}/${SERVICE}:${SERVICE_PATH}/${SERVICE}

networks:
  management:
    external: true
