services:
  komodo:
    image: ghcr.io/moghtech/komodo:latest
    container_name: komodo
    restart: unless-stopped
    networks:
      - db
      - proxy
    ports:
      - 9120:9120
    labels:
      komodo.skip:
      tsdproxy.enable: "true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/${SERVICE}/repo-cache:/repo-cache
      - ${SERVICE_PATH}/${SERVICE}/syncs:/syncs

networks:
  db:
    external: true
  proxy:
    external: true
