services:
  komodo:
    image: ghcr.io/moghtech/komodo-core:1.18.4
    container_name: komodo
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - db
      - proxy
    ports:
      - 9120:9120
    labels:
      komodo.skip:
      tsdproxy.enable: "true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/${SERVICE}/core/repo-cache:/repo-cache
      - ${SERVICE_PATH}/${SERVICE}/core/syncs:/syncs

  mongo:
    image: mongo:8.0.11
    container_name: mongo
    restart: unless-stopped
    command: --quiet --wiredTigerCacheSizeGB 0.25
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DATABASE_PASSWORD}
    labels:
      komodo.skip:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/${SERVICE}/mongo/data:/data/db
      - ${SERVICE_PATH}/${SERVICE}/mongo/config:/data/configdb

networks:
  db:
    external: true
  proxy:
    external: true
