services:  
  komodo-core:
    image: ghcr.io/mbecker20/komodo:latest
    container_name: komodo-core
    restart: unless-stopped
    networks:
      - db
      - internal
    ports:
      - 9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${MONGO_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${MONGO_PASSWORD}
    labels:
      komodo.skip:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_PATH}/komodo/repo-cache:/repo-cache

  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:latest
    container_name: komodo-periphery
    restart: unless-stopped
    networks:
      - internal
    environment:
      PERIPHERY_REPO_DIR: "${SERVICE_PATH}/komodo/data/repos"
      PERIPHERY_STACK_DIR: "${SERVICE_PATH}/komodo/data/stacks"
      PERIPHERY_SSL_KEY_FILE: "${SERVICE_PATH}/komodo/data/ssl/key.pem"
      PERIPHERY_SSL_CERT_FILE: "${SERVICE_PATH}/komodo/data/ssl/cert.pem"
    labels:
      komodo.skip:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${SERVICE_PATH}/komodo/data:${SERVICE_PATH}/komodo/data

networks:
  db:
    external: true
  internal:
    external: true